# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='cases',
            field=models.TextField(default='cardiac'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
